# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json
# Authorization: Token 9a348086a4c9c51b7b6c1df413f7e7672385be98

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 9a348086a4c9c51b7b6c1df413f7e7672385be98

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/120/
Content-Type: application/json
Authorization: Token 9a348086a4c9c51b7b6c1df413f7e7672385be98

{
  "status": "CLOSED"
}
###
# попытка поменять объявление DRAFT
PATCH {{baseUrl}}/advertisements/140/
Content-Type: application/json
Authorization: Token 846804e0b34b043c70892ba1db01fb5bf1563fcc

{
  "status": "DRAFT"
}


###
# удаление обьявление
DELETE {{baseUrl}}/advertisements/48/
Content-Type: application/json
Authorization: Token 9a348086a4c9c51b7b6c1df413f7e7672385be98


###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=3
Content-Type: application/json

###


# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2020-10-01
Content-Type: application/json


###

# фильтрация по статусу
GET {{baseUrl}}/advertisements/?search=open
Content-Type: application/json


###
# добавление в избранное
POST {{baseUrl}}/advertisements/1/favorites/
Content-Type: application/json
Authorization: Token 9a348086a4c9c51b7b6c1df413f7e7672385be98
