# Generated by Django 5.0.2 on 2024-02-15 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0004_remove_advertisement_favorites_favorites'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorites',
        ),
    ]
